[package]
name = "rustorrent-web"
version = "0.1.0"
authors = ["Alexander Korolev <kilork@yandex.ru>"]
edition = "2018"
build = "build.rs"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
actix-files = "0.1"
actix-web = { version = "1.0", features = ["rustls"] }
handlebars = "2.0"
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
failure = "0.1"
exitfailure = "0.5"
log = "0.4"
env_logger = "0.6"
rustorrent = { path = "../rustorrent" }
actix-web-static-files = { path = "../actix-web-static-files" }

