[package]
name = "rsbt-frontend"
version = "0.1.0"
authors = ["Alexander Korolev <kilork@yandex.ru>"]
edition = "2018"
build = "build.rs"

[features]
default = []

ui = []

[dependencies]
actix-web-static-files = "2"

[build-dependencies]
actix-web-static-files = "2"
