version: "3.7"
services:
  bttracker:
    image: henkel/bittorrent-tracker
  transmission:
    image: kilork/rustorrent-transmission
    build: docker/transmission
    volumes:
      - "data:/data"
  qbittorrent:
    image: kilork/rustorrent-qbittorrent
    build: docker/qbittorrent
    volumes:
      # - "config:/config"
      - "data:/downloads"
    ports:
      - 8080:8080
  bittorrent-file:
    image: kilork/rustorrent-bittorent-file
    build: docker/bittorent-file
    volumes:
      - "data:/data"
  app:
    image: kilork/rustorrent-app
    build: .
    volumes:
      - "data:/data"
      - "./target/x86_64-unknown-linux-musl/debug:/app/:Z"

volumes:
  data:
  # config:
