[package]
name = "flat-storage-mmap"
version = "0.1.0"
authors = ["Alexander Korolev <kilork@yandex.ru>"]
edition = "2018"

[dependencies]

failure = "0.1"
futures = "0.3"

flat-storage = { path = "../flat-storage" }

memmap = "0.7"

log = "0.4"